name: test

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - master

jobs:
  test-node:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["20", "16"]
        typescript: ["5.0"]
    name: TS ${{ matrix.typescript }} Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
      - run: npm run compile
      - run: npm install --no-save typescript@${{ matrix.typescript }}
      - run: npm run test

  lint:
    runs-on: ubuntu-latest
    name: Lint and Typecheck
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "20"
      - run: npm install
      - run: npm run compile
      - run: npm run lint
      - run: npm run typecheck
